import Head from "next/head";
import Image from "next/image";
import React from "react";
import Typer from "../components/Typer";

export default function Home() {
  return (
    <div className="main-container">
      <Head>
        <title className="bg-blue-500 hidden">Create Next App</title>
        <meta name="description" content="Generated by create next app" />

        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="true"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Roboto+Mono:wght@400;500;600&display=swap"
          rel="stylesheet"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="relative">
        <Typer />
      </main>

      <footer className=""></footer>
    </div>
  );
}
